DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS quizzes CASCADE;
DROP TABLE IF EXISTS questions CASCADE;
DROP TABLE IF EXISTS alternatives CASCADE;
DROP TABLE IF EXISTS tests CASCADE;
DROP TABLE IF EXISTS answers CASCADE;

CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL
);

CREATE TABLE quizzes (
  id SERIAL PRIMARY KEY NOT NULL,
  title VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  cut_note INTEGER NOT NULL,
  time_limit INTEGER NOT NULL,
  url_quiz_image VARCHAR(255) NOT NULL,
  owner_id INTEGER REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE questions (
  id SERIAL PRIMARY KEY NOT NULL,
  question TEXT NOT NULL,
  url_picture_link TEXT NOT NULL,
  quiz_id INTEGER REFERENCES quizzes(id) ON DELETE CASCADE
);

CREATE TABLE altenatives (
  id SERIAL PRIMARY KEY NOT NULL,
  alternative TEXT NOT NULL,
  is_correct BOOLEAN NOT NULL,
  question_id INTEGER REFERENCES questions(id) ON DELETE CASCADE
);

CREATE TABLE tests (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE
  quiz_id INTEGER REFERENCES quizzes(id) ON DELETE CASCADE
  date_created TIMESTAMP NOT NULL,
  finish_date TIMESTAMP NOT NULL
);

CREATE TABLE answers (
  id SERIAL PRIMARY KEY NOT NULL,
  question_id INTEGER NOT NULL,
  alternative_id INTEGER NOT NULL,
  test_id INTEGER REFERENCES tests(id) ON DELETE CASCADE
);


